image: docker

before_script:
  - apt-get update
  - apt-get install -y gcc g++

c-build: 
    stage: build
    script: 
        - gcc src/c-test.c -o cbinary

    artifacts:
        paths:
            - cbinary
    cache:
        paths: 
            - "*.o"

cpp-build:
    stage: build
    script:
        - g++ src/testcpp.cpp -o cppbinary
    artifacts:
        paths:
            - cppbinary
    cache:
        paths: 
            - "*.o"

test:
  stage: test
  script:
    - ./cbinary
    - ./cppbinary