image: gcc

c-build: 
    stage: build
    script: 
        - gcc src/c-test.c -o cbinary

    artifacts:
        paths:
            - mybinary
    cache:
        paths: 
            - "*.o"

cpp-build:
    stage: build
    script:
        - gcc src/testcpp.cpp -o cppbinary
    artifacts:
        paths:
            - cppbinary
    cache:
        paths: 
            - "*.o"

test:
  stage: test
  script:
    - ./mybinary
    - ./cppbinary